
//listing of all techniques and passes with embedded asm listings 

technique Technique1
{
    pass Default
    {
        //No embedded vertex shader
        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 10.1
            //
            // Parameters:
            //
            //   sampler2D uImage0;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   uImage0      s0       1
            //
            
                ps_3_0
                dcl_texcoord v0.xy
                dcl_2d s0
                texld oC0, v0, s0
            
            // approximately 1 instruction slot used (1 texture, 0 arithmetic)
            };
    }
}

